language: ruby

rvm:
  - 1.9.3-p547
  - 2.0.0

env:
  - "BUNDLE_GEMFILE=$TRAVIS_BUILD_DIR/warden-client/Gemfile"
  - "BUNDLE_GEMFILE=$TRAVIS_BUILD_DIR/warden-protocol/Gemfile"
  - "BUNDLE_GEMFILE=$TRAVIS_BUILD_DIR/em-warden-client/Gemfile"

before_install: bundle install

script:
  - if [[ "$BUNDLE_GEMFILE" == *"/warden-client"* ]]; then cd $TRAVIS_BUILD_DIR/warden-client && bundle exec rspec spec; fi
  - if [[ "$BUNDLE_GEMFILE" == *"/warden-protocol"* ]]; then cd $TRAVIS_BUILD_DIR/warden-protocol && bundle exec rspec spec; fi
  - if [[ "$BUNDLE_GEMFILE" == *"/em-warden-client"* ]]; then cd $TRAVIS_BUILD_DIR/em-warden-client && bundle exec rspec spec; fi
