source "http://rubygems.org"

gem "rake"
gem "steno", "~> 0.0.15", :git => 'https://github.com/cloudfoundry/steno.git'
gem "membrane", :git => 'https://github.com/cloudfoundry/membrane.git'
gem "eventmachine", "~> 1.0.0"
gem "em-posix-spawn", :git => 'https://github.com/cloudfoundry/common.git'
gem "sys-filesystem"
gem "yajl-ruby"

gem "em-warden-client", :git => "https://github.com/X-Plat/warden.git", :branch => "x-plat_dev"
gem "warden-client", :git => "https://github.com/X-Plat/warden.git", :branch => "x-plat_dev"
gem "vcap_common", :git => "https://github.com/cloudfoundry/vcap-common.git"

group :spec do
  gem "rspec"
end
